# Basic LAMP stack

version: '2.1'

services:
  # CLI
  cli:
    environment:
      - PANTHEON_SITE
      - PANTHEON_ENV
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro

  # Fake email
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail

  phpmyadmin:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    expose:
      - '80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
