payments:
  badcamp_payment_sponsorship:
    title: 'BADCamp Individual Sponsorship'
    redirect: /registration/confirm
    allowed_amounts:
      - 25
      - 50
      - 100
    amount: 25
    page_title: 'Sponsor The Bay Area Drupal Camp'
  badcamp_payment_organization_sponsorship:
    amount: 400
    title: 'BADCAMP Organization Sponsorship'
    page_title: 'Sponsor The Bay Area Drupal Camp'
    redirect: /sponsors
  badcamp_payment_training:
    title: 'BADCAMP Training'
    page_title: 'Training Registration'
    permission: 'register for trainings'
