module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  badcamp: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  config: 0
  config_direct_save: 0
  contextual: 0
  ctools: 0
  custom_add_another: 0
  daterange_compact: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_reference_revisions: 0
  entity_usage: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  hal: 0
  help: 0
  honeypot: 0
  image: 0
  inline_form_errors: 0
  layout_discovery: 0
  link: 0
  mailchimp: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_attributes: 0
  menu_item_visibility: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  multiple_selects: 0
  node: 0
  options: 0
  owlcarousel: 0
  owlcarousel2: 0
  page_cache: 0
  paragraphs_class: 0
  paragraphs_library: 0
  path: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  recreate_block_content: 0
  schema_metatag: 0
  search: 0
  sendgrid_integration: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_block: 0
  slick: 0
  slick_extras: 0
  slick_ui: 0
  slick_views: 0
  social_media_links: 0
  social_media_links_field: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  viewfield: 0
  views_ui: 0
  webform: 0
  webform_image_select: 0
  webform_ui: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  empty_page: 1000
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  badcamp_2019: 0
  bay_area_camp: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
