module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  badcamp: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  daterange_compact: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  honeypot: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  mailchimp: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  recreate_block_content: 0
  schema_metatag: 0
  search: 0
  sendgrid_integration: 0
  shortcut: 0
  simple_block: 0
  social_media_links: 0
  social_media_links_field: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  xmlsitemap: 1
  views: 10
  empty_page: 1000
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  badcamp_2019: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
