mlid:
  'menu_link_content:ad8a7e1a-7a6f-4115-af99-d6a030f16443':
    roles: {  }
    access_check: false
  'menu_link_content:c9c228a6-84a7-45ab-8468-3e9c6dce9a3f':
    roles: {  }
    access_check: false
  'menu_link_content:71c22bdd-8fdc-4c80-a200-b69036a6f1bb':
    roles: {  }
    access_check: false
  'menu_link_content:2a160e0c-7687-45f3-a3e9-bd7c95274017':
    roles: {  }
    access_check: false
