plugin_selector_id: plugin_select_list
plugin_selector_configuration:
  show_selector_for_single_availability: null
  description: null
  label: null
  required: false
  collect_plugin_configuration: true
  keep_previously_selected_plugins: true
limit_allowed_plugins: true
allowed_plugin_ids:
  'payment_stripe:credit_card': 'payment_stripe:credit_card'
_core:
  default_config_hash: aQM6wHes01iIf_OJ4Wghv8esWZjlJp5ytXKHMZwPiVE
