environment: live
apikey:
  test:
    public: pk_test_EtnF0PPVja3Mxi9oEXxhBRLZ
    secret: sk_test_pjp0PNsaVnrtJSWE6dFF9kUo
    webhook: ''
  live:
    public: pk_live_P8oCz1oWZJCExg0cs8ZiGvox
    secret: sk_live_OTwDlyfmJ6J08xHZwOUSfmCv
    webhook: ''
_core:
  default_config_hash: rvasJJkL462tLuGEfcTDUE_1ReQ_UkXB1gsCVJtCIPg
