#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Composer Install
composer_install ()
{
  cd $PROJECT_ROOT
  composer install --ansi
}

install_theme ()
{
  echo "Installing Gulp CLI..."
  npm install -g gulp-cli
  cd ${PROJECT_ROOT}/web/themes/custom/bay_area_camp/
  echo "Installing Theme Packages..."
  npm install
  echo "Compiling Theme..."
  gulp
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
composer_install
fix_permissions
install_theme
${PROJECT_ROOT}/.docksal/commands/refresh

#-------------------------- END: Execution --------------------------------
